# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be607b401eeaaf511ba209424388bd33cdb5e15c8adb8b02a43de6f16ff2878b82880dcf939528af5b1d7c51f75f53e6de0b4321080a4328111c36b8ae6dab20

test:
  secret_key_base: 3a98e9a4d2e3bf6d8f0dddbf7616dbd9ed0d1f00c6c73ee2592a890a000683ac5af6124522f4fd0bd8aac7370e92b34ca9b9d8a5a04aeae60abc785eb23414cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
